### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by nibreh** [bradenbest/link-saver#2]
Hi !
Testing your app, seams to be great and useful. There is some error

Cannot send session cache limiter - Headers already sent
Cannot modify header information - Headers already sent (postsignup)

I'm looking for correction

cheers

**Comment by bradenbest** [comment]
Care to add more details? I haven't touched the code in several years, and this repository hosts multiple vastly different versions of the app.

the last time I tested this repository (latest version), it worked. 

And just so you know, you have to set up a my SQL database and modify some code for it to work.

My experience with server side programming is abysmal, though, so either way, you'll have to be a lot more specific than that

Thanks for the post anyway.

**Comment by bradenbest** [comment]
Also, I vaguely recall dealing with "headers already sent" errors, and fixing them appropriately. I remember it being an extremely frustrating process.

It means that, well, the headers are already sent, and can't be acted upon. Fixing it just means reordering code so that the sequence of events carries out correctly. And since I already did that when I was making it, those errors wouldn't be showing up unless you somehow messed something up.

**Comment by bradenbest** [comment]
In conclusion, I'm going to close this since there's a lack of documentation/"what have you tried?" on this report.

If you want to reopen it please provide detailed documentation.

Thanks.
